WScentres:
    pattern:  /centres.{_format}
    defaults: { _controller: "chevBoxBundle:WSCentre:list", _format: json }
    requirements:
        _method: GET
        _format: json

WScentre:
    pattern:  /centre/{id}.{_format}
    defaults: { _controller: "chevBoxBundle:WSCentre:infos", _format: json }
    requirements:
        _method: GET
        _format: json
        id: \d