WSbox:
    pattern:  /index.json
    defaults: { _controller: "chevBoxBundle:WSBox:index", _format: json }
    requirements:
      _method:  GET
      _format: JSON

WSbox_show:
    pattern:  /{id}/show.json
    defaults: { _controller: "chevBoxBundle:WSBox:show", _format: json }
    requirements:
      _method:  GET
      _format: JSON