WScentre:
    pattern:  /index.json
    defaults: { _controller: "chevBoxBundle:WSCentre:index", _format: json }
    requirements:
      _method:  GET
      _format: JSON

WScentre_show:
    pattern:  /{id}/show.json
    defaults: { _controller: "chevBoxBundle:WSCentre:show", _format: json }
    requirements:
      _method:  GET
      _format: JSON