chev\PensionBundle\Entity\Facture:
    type: entity
    table: null
    repositoryClass: chev\PensionBundle\Entity\FactureRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        libelle:
            type: string
            length: 255
        dureeSejour:
            type: datetime
        datePaiement:
            type: datetime
        montant:
            type: float
    lifecycleCallbacks: {  }
