chev_pension:
    resource: "@chevPensionBundle/Resources/config/routing.yml"
    prefix:   /

chev_cheval:
    resource: "@chevChevalBundle/Resources/config/routing.yml"
    prefix:   /

chev_box:
    resource: "@chevBoxBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
homepage_pattern:
    resource: "@s4aHomeBundle/Resources/config/routing.yml"
    prefix:   /

s4aUserBundle:
    resource: "@s4aUserBundle/Resources/config/routing.yml"
    prefix:   /