<?php

namespace s4a\WebServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends EntityRepository
{
	public function checkToken($user, $token)
	{
		$entity = $this->findOneByUser($user);
		
		if (!$entity) {
			return false;
		}
		else {
			if ($entity->getToken() == $token) {
				$dateTime = new \DateTime;
				$sessionToken = $entity->getDatetime()->diff($dateTime, true);
				if ($sessionToken->h < 6) {
					return true;
				}
				else {
					return false;
				}
			}
			else {
				return false;
			}
		}
	}
}
