<?php

namespace s4a\WebServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends EntityRepository
{
	public function checkToken($token)
	{
		$entity = $this->findOneByToken($token);
		
		if (!$entity) {
			return false;
		}
		else {
			$dateTime = new \DateTime;
			$sessionToken = $entity->getDatetime()->diff($dateTime, true);
			if ($sessionToken->h < 6) {
				return true;
			}
			else {
				return false;
			}
		}
	}
}
