cheval_race:
    pattern:  /
    defaults: { _controller: "chevChevalBundle:Race:index" }

cheval_race_show:
    pattern:  /{id}/show
    defaults: { _controller: "chevChevalBundle:Race:show" }

cheval_race_new:
    pattern:  /new
    defaults: { _controller: "chevChevalBundle:Race:new" }

cheval_race_create:
    pattern:  /create
    defaults: { _controller: "chevChevalBundle:Race:create" }
    requirements: { _method: post }

cheval_race_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "chevChevalBundle:Race:edit" }

cheval_race_update:
    pattern:  /{id}/update
    defaults: { _controller: "chevChevalBundle:Race:update" }
    requirements: { _method: post }

cheval_race_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "chevChevalBundle:Race:delete" }
    requirements: { _method: post }
