cheval_vaccin:
    pattern:  /
    defaults: { _controller: "chevChevalBundle:Vaccin:index" }

cheval_vaccin_show:
    pattern:  /{id}/show
    defaults: { _controller: "chevChevalBundle:Vaccin:show" }

cheval_vaccin_new:
    pattern:  /new
    defaults: { _controller: "chevChevalBundle:Vaccin:new" }

cheval_vaccin_create:
    pattern:  /create
    defaults: { _controller: "chevChevalBundle:Vaccin:create" }
    requirements: { _method: post }

cheval_vaccin_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "chevChevalBundle:Vaccin:edit" }

cheval_vaccin_update:
    pattern:  /{id}/update
    defaults: { _controller: "chevChevalBundle:Vaccin:update" }
    requirements: { _method: post }

cheval_vaccin_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "chevChevalBundle:Vaccin:delete" }
    requirements: { _method: post }
