chev_pension_homepage:
    pattern:  /pension
    defaults: { _controller: chevPensionBundle:Default:index }

chevPensionBundle_paiement_type:
    resource: "@chevPensionBundle/Resources/config/routing/typepaiement.yml"
    prefix:   /paiement/type

chevPensionBundle_paiement:
    resource: "@chevPensionBundle/Resources/config/routing/paiement.yml"
    prefix:   /paiement
chevPensionBundle_facture:
    resource: "@chevPensionBundle/Resources/config/routing/facture.yml"
    prefix:   /facture