chevPensionBundle_paiement_type:
    resource: "@chevPensionBundle/Resources/config/routing/typepaiement.yml"
    prefix:   /paiement/type

chevPensionBundle_paiement:
    resource: "@chevPensionBundle/Resources/config/routing/paiement.yml"
    prefix:   /paiement
chevPensionBundle_facture:
    resource: "@chevPensionBundle/Resources/config/routing/facture.yml"
    prefix:   /facture
chevPensionBundle_supplement:
    resource: "@chevPensionBundle/Resources/config/routing/supplement.yml"
    prefix:   /supplement
chevPensionBundle_typelogement:
    resource: "@chevPensionBundle/Resources/config/routing/typelogement.yml"
    prefix:   /typelogement