parameters:
#    chev_pension.example.class: chev\PensionBundle\Example

services:
#    chev_pension.example:
#        class: %chev_pension.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
