<?php

namespace chev\PensionBundle\Entity;

use Doctrine\ORM\EntityRepository, 
    Doctrine\ORM\Query;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends EntityRepository
{
	public function findAvecMontant($id) {
	    try {
    		$em = $this->getEntityManager();
            $query = 'SELECT f AS facture, t.prix'
                   . ' FROM chevPensionBundle:Facture f'
                   . ' JOIN f.box b'
                   . ' JOIN b.type t'
                   . ' WHERE f.id = :id';
    		$facture = $em->createQuery($query)
    					  ->setParameter(':id', $id)
    					  ->getOneOrNullResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
        if($facture == null)
            return null;
        $intervalDates = $facture['facture']->getDateDebut()->diff($facture['facture']->getDateFin(), true);
        $intervalJours = $intervalDates->days;
        $facture['montant'] = $intervalJours*$facture['prix'];
        return $facture;

	}
}
