<?php

namespace chev\PensionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PensionRepository extends EntityRepository
{
}
