<?php

namespace chev\PensionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SupplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplementRepository extends EntityRepository
{
}
