<?php

namespace chev\PensionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeLogementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLogementRepository extends EntityRepository
{
	/**
     * Trouver les type de Logements par le gérant
     * 
     * @param User $gerant Le gérant
     * 
     * @return Entity
     */
	public function findByGerant($gerant) {
		return $this->_em
                ->createQuery('SELECT tl FROM chevPensionBundle:TypeLogement tl
                               JOIN tl.centre c
                               WHERE c.gerant = :gerant')
                ->setParameter(':gerant', $gerant)
                ->getResult();
	}
	/**
     * Trouver un type de logement par l'id et le gérant
     * 
     * @param User $gerant Le gérant
     * @param int $id l'id
     * 
     * @return Entity
     */
	public function findOneByGerant($gerant, $id) {
		return $this->_em
                ->createQuery('SELECT tl FROM chevPensionBundle:TypeLogement tl
                               JOIN tl.centre c
                               WHERE c.gerant = :gerant
                               AND tl.id = :id')
                ->setParameter(':gerant', $gerant)
				->setParameter(':id', $id)
                ->getOneOrNullResult();
	}
}
