<?php

namespace chev\ChevalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Cheval_VaccinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cheval_VaccinRepository extends EntityRepository
{
}
