<?php

namespace chev\ChevalBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NourritureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NourritureRepository extends EntityRepository
{
	/**
     * Trouver tous les nourritures par le centre ayant ce gérant
     * 
     * @param User $gerant Le gérant
     *
     * @return Tableau d'entités
     */
    public function findByCentreGerant($gerant) {
        return $this->_em
                ->createQuery('SELECT r FROM chevChevalBundle:Race r
                               JOIN r.centre c
                               WHERE c.gerant = :gerant')
                ->setParameter(':gerant', $gerant)
                ->getResult();
    }
    
    /**
     * Trouver une nourriture par le centre ayant ce gérant et l'id
     * 
     * @param User $gerant Le gérant
     * @param int $id l'id
     * 
     * @return Entity
     */
    public function findOneByCentreGerant($gerant, $id) {
        return $this->_em
                ->createQuery('SELECT r FROM chevChevalBundle:Race r
                               JOIN r.centre c
                               WHERE c.gerant = :gerant
                               AND r.id = :id')
                ->setParameter(':gerant', $gerant)
                ->setParameter(':id', $id)
                ->getOneOrNullResult();
    }
}
