<?php

namespace chev\BoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxRepository extends EntityRepository
{
    /**
     * Trouver tous les box par le centre ayant ce gérant
     * 
     * @param User $gerant Le gérant
     *
     * @return Tableau d'entités
     */
    public function findByCentreGerant($gerant) {
        return $this->_em
                ->createQuery('SELECT b FROM chevBoxBundle:Box b
                               JOIN b.centre c
                               WHERE c.gerant = :gerant')
                ->setParameter(':gerant', $gerant)
                ->getResult();
    }
    
    /**
     * Trouver un box par le centre ayant ce gérant et l'id
     * 
     * @param User $gerant Le gérant
     * @param int $id l'id
     * 
     * @return Entity
     */
    public function findOneByCentreGerant($gerant, $id) {
        return $this->_em
                ->createQuery('SELECT b FROM chevBoxBundle:Box b
                               JOIN b.centre c
                               WHERE c.gerant = :gerant
                               AND b.id = :id')
                ->setParameter(':gerant', $gerant)
                ->setParameter(':id', $id)
                ->getOneOrNullResult();
    }
	
	public function getTotalBox($gerant)
	{
		$allBox = $this->findByBoxAndCentreGerant($gerant);
		$nbBox = count($allBox);
		
		$i = 0;
		foreach ($allBox as $box) {
			if($box->getCheval() == null) {
				$i ++;
			}
		}
		return array(
			'nbBox' => $nbBox, 
			'boxVide' => $i
		);
	}
}
