<?php

namespace chev\BoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreRepository extends EntityRepository
{
    /**
     * Récupère les informations des centres pour le webservice
     * 
     * @return array Les centres
     */
    public function WSCentres() {
        $centres =  $this->_em
                ->createQuery('SELECT c.id, c.nom, c.adresse, c.codePostal, c.ville
                               FROM chevBoxBundle:Centre c
                               ORDER BY c.codePostal')
                ->getResult();
        return $centres;
    }
    
    /**
     * Récupère les informations d'un centre pour le webservice
     * 
     * @return array Le centre
     */
    public function WSCentre($id) {
        $centre =  $this->_em
                ->createQuery('SELECT c.id, c.nom, c.adresse, c.codePostal, c.ville, c.telephone, c.date, c.dateAjout, g.firstname, g.lastname
                               FROM chevBoxBundle:Centre c
                               JOIN c.gerant g
                               WHERE c.id = :id')
                ->setParameter(':id', (int) $id)
                ->getSingleResult();
        if(!empty($centre)) {
            $centre['date'] = $centre['date']->format('d/m/Y');
            $centre['dateAjout'] = $centre['dateAjout']->format('d/m/Y');
        }
        return $centre;
    }
}
