chevChevalBundle_cheval:
    resource: "@chevChevalBundle/Resources/config/routing/cheval.yml"
    prefix:   /cheval
chevChevalBundle_cheval_race:
    resource: "@chevChevalBundle/Resources/config/routing/race.yml"
    prefix:   /cheval/race
chevChevalBundle_equipement:
    resource: "@chevChevalBundle/Resources/config/routing/equipement.yml"
    prefix:   /equipement

WSchevChevalBundle_cheval:
    resource: "@chevChevalBundle/Resources/config/routing/WScheval.yml"
    prefix:   /ws/cheval
WSchevChevalBundle_cheval_race:
    resource: "@chevChevalBundle/Resources/config/routing/WSrace.yml"
    prefix:   /ws/cheval/race
WSchevChevalBundle_equipement:
    resource: "@chevChevalBundle/Resources/config/routing/WSequipement.yml"
    prefix:   /ws/equipement