chevChevalBundle_cheval:
    resource: "@chevChevalBundle/Resources/config/routing/cheval.yml"
    prefix:   /cheval
chevChevalBundle_cheval_nourriture:
    resource: "@chevChevalBundle/Resources/config/routing/nourriture.yml"
    prefix:   /cheval/nourriture
chevChevalBundle_equipement:
    resource: "@chevChevalBundle/Resources/config/routing/equipement.yml"
    prefix:   /equipement