chevChevalBundle_cheval:
    resource: "@chevChevalBundle/Resources/config/routing/cheval.yml"
    prefix:   /cheval
chevChevalBundle_cheval_nourriture:
    resource: "@chevChevalBundle/Resources/config/routing/nourriture.yml"
    prefix:   /cheval/nourriture
chevChevalBundle_equipement:
    resource: "@chevChevalBundle/Resources/config/routing/equipement.yml"
    prefix:   /equipement

WSchevChevalBundle_cheval:
    resource: "@chevChevalBundle/Resources/config/routing/WScheval.yml"
    prefix:   /ws/cheval
WSchevChevalBundle_equipement:
    resource: "@chevChevalBundle/Resources/config/routing/WSequipement.yml"
    prefix:   /ws/equipement