chevChevalBundle_cheval_race:
    resource: "@chevChevalBundle/Resources/config/routing/race.yml"
    prefix:   /cheval/race
    
chevChevalBundle_cheval:
    resource: "@chevChevalBundle/Resources/config/routing/cheval.yml"
    prefix:   /cheval
    
chevChevalBundle_equipement:
    resource: "@chevChevalBundle/Resources/config/routing/equipement.yml"
    prefix:   /equipement
