chevChevalBundle_cheval_race:
    resource: "@chevChevalBundle/Resources/config/routing/race.yml"
    prefix:   /cheval/race
    
chevChevalBundle_cheval_vaccin:
    resource: "@chevChevalBundle/Resources/config/routing/vaccin.yml"
    prefix:   /cheval/vaccin
    
chevChevalBundle_cheval:
    resource: "@chevChevalBundle/Resources/config/routing/cheval.yml"
    prefix:   /cheval