<?php
namespace s4a\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegisterRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	function userPagination($perPage = 30, $page = 1) {
		return $this->_em
				->createQuery('SELECT u FROM s4aUserBundle:User u')
		       ->setMaxResults($perPage)
		       ->setFirstResult($perPage * ($page - 1))
				->getResult();
	}
	function searchInAll(){
		
	}
	function count() {
		return (int)$this->_em
				->createQuery('SELECT COUNT(u) FROM s4aUserBundle:User u')
				->getSingleScalarResult();
	}

}
