chevBoxBundle_centre:
    resource: "@chevBoxBundle/Resources/config/routing/centre.yml"
    prefix:   /centre
chevBoxBundle_centre_box:
    resource: "@chevBoxBundle/Resources/config/routing/box.yml"
    prefix:   /centre/box
chevBoxBundle_centre_typebox:
    resource: "@chevBoxBundle/Resources/config/routing/typebox.yml"
    prefix:   /centre/typebox
chevBoxBundle_centre_pature:
    resource: "@chevBoxBundle/Resources/config/routing/pature.yml"
    prefix:   /centre/pature

WSchevBoxBundle_centre:
    resource: "@chevBoxBundle/Resources/config/routing/WScentre.yml"
    prefix:   /ws/centre
WSchevBoxBundle_centre_box:
    resource: "@chevBoxBundle/Resources/config/routing/WSbox.yml"
    prefix:   /ws/centre/box
WSchevBoxBundle_centre_typebox:
    resource: "@chevBoxBundle/Resources/config/routing/WStypebox.yml"
    prefix:   /ws/centre/typebox
WSchevBoxBundle_centre_pature:
    resource: "@chevBoxBundle/Resources/config/routing/WSpature.yml"
    prefix:   /ws/centre/pature