chevBoxBundle_centre:
    resource: "@chevBoxBundle/Resources/config/routing/centre.yml"
    prefix:   /centre
chevBoxBundle_centre_box:
    resource: "@chevBoxBundle/Resources/config/routing/box.yml"
    prefix:   /centre/box
chevBoxBundle_centre_pature:
    resource: "@chevBoxBundle/Resources/config/routing/pature.yml"
    prefix:   /centre/pature