parameters:
#    chev_box.example.class: chev\BoxBundle\Example

services:
#    chev_box.example:
#        class: %chev_box.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
